name: slippi-ai test cases

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        os: ['ubuntu-latest']

    steps:
    - uses: actions/checkout@v4

    # See https://github.com/pypa/pip/issues/11281
    - name: Install
      run: |
        pip install tensorflow ray
        pip install -r requirements.txt
        pip install .

    - name: Test Imitation
      run: ./tests/training_test.sh

    - name: Test Imitation with Restore
      run: ./tests/training_test.sh --config.restore_pickle=data/checkpoints/demo

    - name: Test RL with Fake Data
      run: ./tests/train_rl.sh

    - name: Test RL with Fake Data + Restore
      run: ./tests/train_rl.sh --config.teacher="" --config.restore=data/checkpoints/rl_demo

    - name: Test train_two with Fake Data
      run: ./tests/train_two.sh
